Updated graph function so that it works with multiple data inputs
AlmasTalkingDogs/Doge pull request #18
Opened 2020-02-19 03:13 UTC by chenfeiyu132

#10

2020-02-19 03:16 UTC, cwlowder requested changes

2020-02-19 03:16 UTC, cwlowder commented on server/res/graph.html
> +            var feedSocket2 = new WebSocket(getWebSocketURI("/ws/data/random"));
Why is this the second feed socket?

2020-02-19 03:16 UTC, cwlowder commented on server/res/graph.html
>          <script>
I'd prefer if we put this code into a file called graph.js. That way other htmls can use it. You will need to add a static definition for this in app.py

2020-02-19 03:16 UTC, cwlowder commented on server/res/graph.html
> +                  // if(counter > 50) {
Delete commented out code

2020-02-19 03:16 UTC, cwlowder commented on server/res/graph.html
> +                    datalist[config].push(msg_data[index]);
You should do the remove of old data here. So when the size of the data > 500, start removing elements?

2020-02-19 20:42 UTC, cwlowder requested changes

2020-02-19 20:42 UTC, cwlowder commented on server/res/graph.html
>              console.log("LOG LOG LOG")
We should remove this console.log

2020-02-19 20:42 UTC, cwlowder commented on server/res/graph.html
> +                    //Plotly.update(divId, datalist[key], layout, index)
Remove this comment

2020-02-19 20:42 UTC, cwlowder commented on server/res/graph.html
> +                  console.log(newdata)
Remove this

2020-02-19 20:42 UTC, cwlowder commented on server/res/graph.html
> +                console.log(msg)
Maybe remove this too?

2020-02-27 17:34 UTC, chenfeiyu132 commented on server/res/graph.html
> +            var feedSocket2 = new WebSocket(getWebSocketURI("/ws/data/random"));
Because you named it this way

2020-02-29 21:18 UTC, chenfeiyu132 commented on server/res/graph.html
> +                console.log(msg)
Nah

2020-02-29 21:18 UTC, chenfeiyu132 commented on server/res/graph.html
> +                console.log(msg)
It's useful for debugging

2020-02-29 21:23 UTC, cwlowder requested changes
Change max number to 100

2020-02-29 21:24 UTC, cwlowder approved these changes
Looks great!

2020-02-29 21:25 UTC, merged